#!/usr/bin/env python3
"""
Fetch citation counts from the InspireHEP public API for every entry in
_bibliography/papers.bib, and write them to _data/citations.yml.

Unlike Google Scholar, InspireHEP has a free, public, unauthenticated REST
API, so this doesn't need scraping, an API key, or a browser session.

Matching strategy:
  BibTeX entries generated by INSPIRE use the INSPIRE "texkey" as the
  citation key (e.g. `Agashe:2020wph`), so we query InspireHEP directly by
  texkey. This is a more reliable match than title or arXiv-ID matching.

Usage:
    python3 scripts/fetch_inspirehep_citations.py

Requires: requests, pyyaml
    pip install requests pyyaml
"""
import re
import sys
from datetime import date, timezone
from pathlib import Path

import requests
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = REPO_ROOT / "_bibliography" / "papers.bib"
OUT_PATH = REPO_ROOT / "_data" / "citations.yml"

INSPIRE_API = "https://inspirehep.net/api/literature"
# Keep well under Inspire's rate limits: batch every entry into one query
# instead of one request per paper.
BATCH_SIZE = 50


# @comment / @string / @preamble blocks aren't publication entries and can
# span multiple lines without a comma, which would otherwise confuse the key
# extraction below.
_NON_ENTRY_TYPES = {"comment", "string", "preamble"}


def extract_texkeys(bib_text: str) -> list[str]:
    """Pull BibTeX citation keys, e.g. `@article{Agashe:2020wph,` -> Agashe:2020wph."""
    keys = []
    for entry_type, key in re.findall(r"^@(\w+)\{([^,\n]+),", bib_text, flags=re.MULTILINE):
        if entry_type.lower() not in _NON_ENTRY_TYPES:
            keys.append(key.strip())
    return keys


def chunk(seq: list, size: int):
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def fetch_citation_counts(texkeys: list[str]) -> dict[str, dict]:
    """Query InspireHEP for citation_count + title for each texkey, batched."""
    results: dict[str, dict] = {}

    for batch in chunk(texkeys, BATCH_SIZE):
        query = " or ".join(f'texkey:"{key}"' for key in batch)
        params = {
            "q": query,
            "fields": "texkeys,citation_count,titles,earliest_date",
            "size": len(batch),
        }
        resp = requests.get(INSPIRE_API, params=params, timeout=30)
        resp.raise_for_status()
        hits = resp.json().get("hits", {}).get("hits", [])

        for hit in hits:
            record_id = hit.get("id", "")
            metadata = hit.get("metadata", {})
            hit_texkeys = metadata.get("texkeys", [])
            citation_count = metadata.get("citation_count", 0)
            titles = metadata.get("titles", [])
            title = titles[0]["title"] if titles else ""
            earliest_date = metadata.get("earliest_date", "")
            year = earliest_date[:4] if earliest_date else ""

            # A record can be filed under more than one texkey; credit them all.
            for key in hit_texkeys:
                if key in texkeys:
                    results[key] = {
                        "citations": citation_count,
                        "title": title,
                        "year": year,
                        "record_id": record_id,
                    }

    return results


def main() -> int:
    if not BIB_PATH.exists():
        print(f"Bibliography not found at {BIB_PATH}", file=sys.stderr)
        return 1

    bib_text = BIB_PATH.read_text(encoding="utf-8")
    texkeys = extract_texkeys(bib_text)
    print(f"Found {len(texkeys)} bibliography entries.")

    results = fetch_citation_counts(texkeys)

    missing = [key for key in texkeys if key not in results]
    if missing:
        print(f"Warning: no InspireHEP match for {len(missing)} entries:", file=sys.stderr)
        for key in missing:
            print(f"  - {key}", file=sys.stderr)

    output = {
        "metadata": {
            "last_updated": date.today().isoformat(),
            "source": "inspirehep",
        },
        "papers": results,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        yaml.dump(output, f, sort_keys=True, allow_unicode=True, default_flow_style=False)

    print(f"Wrote {len(results)} citation counts to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())